# Generated by Django 4.1.7 on 2023-02-19 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thumbnailsize',
            name='height',
            field=models.IntegerField(blank=True, null=True, verbose_name='height'),
        ),
        migrations.AlterField(
            model_name='thumbnailsize',
            name='tier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='core.tier', verbose_name='tier'),
        ),
        migrations.AlterField(
            model_name='thumbnailsize',
            name='width',
            field=models.IntegerField(blank=True, null=True, verbose_name='width'),
        ),
        migrations.AlterField(
            model_name='tier',
            name='can_generate_expire_link',
            field=models.BooleanField(default=False, help_text='Specify whether user can generate expiring image links', verbose_name='can_generate_expire_link'),
        ),
        migrations.AlterField(
            model_name='tier',
            name='has_og_image_access',
            field=models.BooleanField(default=False, help_text='Specify whether user can access original size image', verbose_name='has_og_image_access'),
        ),
        migrations.AlterField(
            model_name='tier',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='name'),
        ),
    ]
