# Generated by Django 4.1.7 on 2023-02-19 19:01

import core.models.image
import core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_image_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='id',
        ),
        migrations.AlterField(
            model_name='image',
            name='og_file',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.image.get_upload_to, validators=[core.validators.img_extension_validator]),
        ),
        migrations.AlterField(
            model_name='image',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='thumbnail',
            name='file',
            field=models.ImageField(upload_to=core.models.image.get_upload_to, validators=[core.validators.img_extension_validator]),
        ),
    ]
